run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - revive
    - gocritic
    - bodyclose

linters-settings:
  govet:
    disable:
      - fieldalignment
      - unusedwrite
      - shadow
  errcheck:
    exclude-functions:
      - (io.Writer).Write
      - (net/http.ResponseWriter).Write
      - (*compress/gzip.Writer).Write
      - io.Copy
      - fmt.Fprintf
      - fmt.Fprint
      - fmt.Fprintln
      - (encoding/json.Encoder).Encode
      - (*encoding/json.Encoder).Encode
  revive:
    rules:
      - name: exported
        disabled: true
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
      - exitAfterDefer

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - noctx
        - bodyclose
    - path: cmd/
      linters:
        - noctx
    - path: sdk/
      linters:
        - errcheck
    - linters:
        - gosec
      text: "G107|G110|G306|G404"
    - linters:
        - staticcheck
      text: "SA1012"
    - linters:
        - prealloc
      text: "Consider pre-allocating"
  max-issues-per-linter: 0
  max-same-issues: 0
